### ISSUE TITLE
"I-Feel" support for "greeya" protocol

### ISSUE THREAD

**Issue by ronnieSVK** [ToniA/arduino-heatpumpir#160]
Dear developer !

Firstly, thank you very much for your time and effort invested in this project !

I would like to kindly ask you to provide the upper mentioned "I-Feel" support for "greeya" protocol.
Sadly the "greeyac" commands are not registered by our AirCondition, however the factory remote controller is equipped with this function, which is proofed-tested, since we are using our device only with this option.

If i can provide any help in solving this request, just let me know !

Thank you
Best wishes

**Comment by ronnieSVK** [comment]
Dear @ToniA ,

is here any chance please to cooperate on this request please ? I have to find a solution because of dimensions of our apartment and presence of a child i have to use our climate device only via i-feel function. The "greeyac" commands are not accepted by coolexpert and "greeya" protocol misses this function.
As i wrote upper, just let me know if i can help/contribute in this !

Thank you Toni !

Greetings !

**Comment by ToniA** [comment]
Hi, sorry for not responding earlier. So this 'I-Feel' is a special command (temperature measurement) sent periodically by the remote controller? This would need a protocol decoding from a real remote controller, this would tell us the data that should be sent. See https://github.com/ToniA/Raw-IR-decoder-for-Arduino for instructions.

I can't help much on decoding, as I don't have access to any Gree device.

**Comment by ronnieSVK** [comment]
Hey Toni ! 
Thank you very much for your response !
Exactly, the i-feel function is what you described. Sadly i have to use it for proper and safe function. Couple of ESP32S are prepared including remote receiver/transmitter, so i can do whatever is needed/whatever im able to do. I think couple of users facing this issue will be glad for this function. The only question is, how should i perform the signal capture ? I mean not technically (ill check your provided link for that), but from the perspective that the remote measures the ambient temp, so if we would like to capture the values for different temperatures-temperature range, i have to simulate those ambient temperatures and also save them, to know which Ir code belongs to which ambient temperature value. It is like this please ? Do you know maybe, how this capture/decoding was done for the "greeyac" protocol please ?

Thank you !
Greetings
Ronnie

**Comment by Nateonas** [comment]
I don't have an I-feel AC, but for my setup I attached a DHT22-sensor to the ESP. I installed ESPeasy, so both heatpumpIR and the DHT-sensor are supported. The room-temperature is sent to my Domoticz controller. With this setup it is possible to control the AC based on the temperature in the room from Domoticz (or Home Assistant of course).
You probably will need to find the I-feel IR-codes sent by the remote, but perhaps you can use the temperature from a DHT-sensor to include the temperature.

**Comment by ronnieSVK** [comment]
Hi @Nateonas !
Thank you very much for your contribution !

This is exactly what i would like to achieve. Im running HomeAssistant, so my goal is to build Ir remote on ESP32 with ESPHome and link my room temperature sensor to it. But for this, i have to activate/use the "I-Feel" option, which will measure the ambient temperature from AC remote controllers sensors (in this case from sensor linked to ESP32) otherwise the AC unit will use its internal ambient temp sensor. So the "I-Feel" is the way to tell AC to use the different sensor, and also to send/receive/behave regarding to measured values. Even if the device is equipped with WiFi module, you can activate "I-Feel" only via remote (i think it is self explaining...) and the remote should be placed in distance/position from where it can transmit every 2minutes the measured values to the AC.

**Comment by Nateonas** [comment]
Would it be possible at all to implement functions for a specific model or brand? It might be easier to develop a separate ESP just to transmit the temperature readings to the AC. What setup did you have in mind?

**Comment by Machaeon** [comment]
Hi @ronnieSVK ! I am using ESPHome with **heatpumpir** platform to send temperature data to my AC. I have specified the **greeyac** protocol, which actually does not match the protocol of my AC. It doesn't allow me to control the AC, but it transmits temperature data properly. But there is one problem - when I control the AC through the integration in my Home Assistant, it disables the iFeel function and I have to reactivate it using the remote.

**Comment by ronnieSVK** [comment]
Hi @Machaeon !

Thank you very much for you reply !
Yes, the behaviour that "i-Feel" turns off everytime the AC is controlled differently as with "i-Feel" enabled Ir Remote Controller (or ESP) is known. I think the reason is, that Remote Controller is transmitting this information (so about i-Feel On/Off status) each time you control your device.
Im glad, that at least the "i-Feel" function works. Maybe some workaround in HA can be made, where after each "command sent" to AC will be "i-Feel ON" command transmitted. Maybe i can check it. 
Could you be please so nice and share your full ESPhome code ? I would like to test out exactly the same config as yours and find some way to make it work (hopefully only till i-Feel will be implemented to other protocols). If you wish, we can stay in touch if i achieve my goal in HA about sending the mentioned command.

Thank you !

**Comment by Machaeon** [comment]
@ronnieSVK, Here is my yaml:
```
esphome:
  name: gree_ir
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gree IR AP"
    password: !secret ap_password 

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key 

web_server:
  port: 80

ota:
  password: !secret ota_password 

logger:

remote_transmitter:
  id: ir_transmit
  pin: D3
  carrier_duty_percent: 50%  

sensor:
  - platform: homeassistant
    id: ha_temperature
    entity_id: sensor.current_temperature

  - platform: template
    id: current_temperature
    lambda: |-
      return (id(ha_temperature).state - 0.5);
    update_interval: 120s  

climate:
  - platform: heatpumpir 
    protocol: greeyac
    name: "AC"
    horizontal_default: middle
    vertical_default: auto
    max_temperature: 30
    min_temperature: 16
    sensor: current_temperature
```
Here's something else that might be important: my AC accepts commands if I specify the **greeyan** protocol but it disables its WiFi adapter when it receives an IR command and I had to reconnect the AC to the network using the mobile app.

**Comment by ronnieSVK** [comment]
Thank you @Machaeon once again !

However (if i good remeber) my code is quite the same, ill check it out in short and provide feedback. At least, we are now "two" with approx. same equipment and issue. If @ToniA provides reply for my questions about capturing Ir codes, maybe we can both cooperate to move things bit quicker.

**Comment by ronnieSVK** [comment]
@Machaeon , feedback from me:
As i expected, my code was the same. 
What i have done : 

- Turned ON AC via factory Remote Controller with i-Feel option ON and put it "out of sight", to avoid communication/temperature transmitting to the unit.

- Turned ON the AC via ESPhome (this was of course just software stuff, since as we know, the AC doesnt capture the "greeya" command) and pointed the Ir Transmitter to face to AC.

The result is, that ESPhome shows the temperature from HA tenperature sensor, but this value isnt transmitted to AC... Now im confused where is the issue, since my Ir Transmitter has LED diode on the board, which light up if command is transmitted. The LED behaves like this if i push command from ESPHome/HA to operate the AC (what again, doesnt work woth greeya for us). BUT, since the temperatures should be transmitted to AC unit every 2minutes, im expecting to "see" this via LED on Ir Transmitter. But this doesnt happen in my case. So im unsure now, if my unit didnt accept anything or the transmitter doesnt send the temp datas. May i please ask you to confirm/deny if your Transmitter has confirmation diode, if you see some activity in 2minute cycles ?

Thank you !

**Comment by Machaeon** [comment]
> * Turned ON the AC via ESPhome (this was of course just software stuff, since as we know, the AC doesnt capture the "**greeya**" command) and pointed the Ir Transmitter to face to AC.

If you used the **greeya** protocol - this may be the source of the problem. In my config I am using **greeyac** and I see a blinking LED every two minutes

**Comment by ronnieSVK** [comment]
@Machaeon sorry mate, this was just a typo in description. Im using the "greeyac" protocol of course

**Comment by Machaeon** [comment]
That's very strange. Can you show your config, maybe we can find a non-obvious problem?

**Comment by ronnieSVK** [comment]
@Machaeon , yeah, im also confused :/

```
esphome:
  name: esphome-web-c66308
  friendly_name: Kitchen Air Condition Ir

esp32:
  board: esp32dev
  framework:
    type: arduino
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  manual_ip:
    static_ip: 192.168.1.65
    gateway: 192.168.1.1
    subnet: 255.255.255.0

remote_transmitter:
  pin: GPIO25
  carrier_duty_percent: 50%

climate:
  - platform: heatpumpir
    protocol: greeyac
    horizontal_default: auto
    vertical_default: up
    max_temperature: 30
    min_temperature: 16
    sensor : kitchen_air_condition_temperature_sensor
    name: "Kitchen Air Condition Ir"

sensor:
  - platform: homeassistant
    name: "Kitchen Air Condition Temperature"
    entity_id: sensor.living_room_th_sensor_temperature
    id: kitchen_air_condition_temperature_sensor

  - platform: template
    id: kitchen_air_condition_current_temeprature
    lambda: |-
      return (id(kitchen_air_condition_temperature_sensor).state);
    update_interval: 120s
```
